export const TRANSLATIONS = {
    zh: {
        title: "AI 进化指南",
        subtitle: "一站式整理全球顶尖 AI 工具、本地搭建教程与提效技巧。助你在这个 AI 时代保持进化。",
        searchPlaceholder: "搜索 AI 工具、教程...",
        all: "全部",
        noResults: "未找到相关工具，换个关键词试试？",
        viewTutorial: "查看教程",
        preparing: "教程筹备中",
        footerCaption: "发现 AI 的力量，提升人类的可能。",
        privacy: "隐私政策",
        disclaimer: "免责声明",
        lang: "English",
        themeSystem: "跟随系统",
        themeLight: "明亮模式",
        themeDark: "暗黑模式",
    },
    en: {
        title: "AI Evolution Guide",
        subtitle: "A curated collection of top AI tools, local setup guides, and productivity tips. Stay ahead in the AI era.",
        searchPlaceholder: "Search AI tools, tutorials...",
        all: "All",
        noResults: "No results found, try another keyword?",
        viewTutorial: "View Tutorial",
        preparing: "Tutorial Coming Soon",
        footerCaption: "Discover the power of AI, enhance human possibilities.",
        privacy: "Privacy Policy",
        disclaimer: "Disclaimer",
        lang: "中文",
        themeSystem: "System",
        themeLight: "Light",
        themeDark: "Dark",
    }
};
